// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModbusScada.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModbusScada.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817170944_AgregarConfiguracionSms")]
    partial class AgregarConfiguracionSms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModbusScada.Api.Models.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Conexion")
                        .HasColumnType("integer");

                    b.Property<string>("ContrasenaUtd")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nsm")
                        .HasColumnType("text");

                    b.Property<string>("Nsue")
                        .HasColumnType("text");

                    b.Property<string>("Nsut")
                        .HasColumnType("text");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer");

                    b.Property<string>("PuertoSerial")
                        .HasColumnType("text");

                    b.Property<string>("Rfc")
                        .HasColumnType("text");

                    b.Property<byte>("SlaveId")
                        .HasColumnType("smallint");

                    b.Property<int?>("SmsHoraEnvio")
                        .HasColumnType("integer");

                    b.Property<int?>("SmsMinutoEnvio")
                        .HasColumnType("integer");

                    b.Property<string>("SmsNumero")
                        .HasColumnType("text");

                    b.Property<int?>("SmsTipoMensaje")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadVerificacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("ModbusScada.Api.Models.LecturaHistorica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RegistroModbusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RegistroModbusId");

                    b.ToTable("LecturasHistoricas");
                });

            modelBuilder.Entity("ModbusScada.Api.Models.RegistroModbus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Direccion")
                        .HasColumnType("integer");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrdenBytes")
                        .HasColumnType("text");

                    b.Property<int>("Tabla")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDato")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.ToTable("RegistrosModbus");
                });

            modelBuilder.Entity("ModbusScada.Api.Models.LecturaHistorica", b =>
                {
                    b.HasOne("ModbusScada.Api.Models.RegistroModbus", "RegistroModbus")
                        .WithMany()
                        .HasForeignKey("RegistroModbusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroModbus");
                });

            modelBuilder.Entity("ModbusScada.Api.Models.RegistroModbus", b =>
                {
                    b.HasOne("ModbusScada.Api.Models.Dispositivo", "Dispositivo")
                        .WithMany("Registros")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("ModbusScada.Api.Models.Dispositivo", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
